apiVersion: 1

datasources:
  # Primary Prometheus datasource for monitoring
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s"
    profiles:
      - grafana

  # Enterprise mode datasource - real Prometheus
  - name: Prometheus-Enterprise
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    profiles:
      - enterprise
