apiVersion: 1

datasources:
  # Free mode datasource - uses mock Prometheus endpoint
  - name: LiteLLM-Mock
    type: prometheus
    access: proxy
    url: http://localhost:4222
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s"
    profiles:
      - grafana

  # Enterprise mode datasource - real Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    profiles:
      - enterprise
